config/routes.rb
Schism::Application.routes.draw do
  root :to => "contests#new", :as => "schism"
  post "/submit", :to => "contests#submit"
  
  get "/login", "/register", "/sign-in", :to => "team_members#sign_in"
  post "/check_user", :to => "team_members#check_user"
  
  
  get "/logout", :to => "team_members#logout"
  
  resources :team_members, :path => "team"
  resources  :contests, :questions
  
  get "/team/:id/contests", :to => "team_members#contests", :as => "user_contests"
  
  match '/404' => 'errors#not_found'
  match '/422' => 'errors#server_error'
  match '/500' => 'errors#server_error'
  

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  attr_accessible :loser_id, :question_id, :winner_id
  
  belongs_to :winner, {:class_name => 'TeamMember', :foreign_key => 'winner_id'}
  belongs_to :loser, {:class_name => 'TeamMember', :foreign_key => 'loser_id'}
  belongs_to :question, {:class_name => 'Question', :foreign_key => 'question_id'}
  
  # ensure the associated records exist
  validates :question, :winner, :loser, :presence => true 
  
  # want to increment a Question's count attribute every time it's used
  after_create :update_question, :update_team_members
  
  def update_question
     self.question.increment
  end
  
  def update_team_members
    self.winner.increment_contests
	self.loser.increment_contests
  end
  
  def to_s
    "#{ self.question.text } Winner: #{ self.winner.name }. Loser: #{ self.loser.name }"
  end

  def self.range( ran=(1..10) ) # eg. Contest.range(20..30), where 1 is the latest record
	min, max = ran.minmax
	total = (max - min) + 1
	
	# don't use 'count', because of deleted records, get the id directly
	db_records = self.last.id
	
	# larger number used to find the lower limit
	# eg. 1..10, (db_records - 10) will yield the lower limit - 1
	# + 1 because we want the record immediately after that
	# ( in a table with 100 records, record 90 is actually the eleventh! )
	db_lower_limit = (db_records - max) + 1
	db_upper_limit = (db_lower_limit + total)
	
	# finally, pop the query
    self.where( :id => (db_lower_limit..db_upper_limit) )
  end	
	
  
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  
  def new
    unless session[:team_member_id]
      flash[:notice] = "You need to sign in to vote."
      return redirect_to '/sign-in'
    end
    
    # pick a random question
    @question = Question.random
    # pick the contestants
    @contestant_a, @contestant_b = TeamMember.pick_two  
    render "new"
  end
  
  def submit
    logger.debug "User clicked button for #{TeamMember.find(params[:winner]).name}"
  
    Contest.create(
      :question_id => params[:question],
      :winner_id => params[:winner],
      :loser_id => params[:loser]
    )
  
    redirect_to :back
  end
  
  def index
    @range = params[:range] || "1-20"
    @x, @y = @range.split("-").map( &:to_i )
    @records = (@y - @x) + 1
    
    if(Contest.first)
      @first_record = Contest.first.id 
      @contests = Contest.includes(:question, :winner, :loser).range( @x..@y ).reverse
    end
  
  end
  
  private
  
end

app/helpers/contests_helper.rb
module ContestsHelper

  def next_range
    # uses @x, @y
	# to "11-20"
	
	spread = (@y - @x) + 1
	"#{@y + 1}-#{@y + spread}"
	
	
  end
  
  def prev_range
    spread = (@y - @x) + 1
	
	# stop less than zero values
	if @x - spread < 1
	  min = 1
	else
	  min = @x - spread
	end
	
	"#{min}-#{@x-1}"
  end
end

app/views/contests/index.html.erb
<% unless @contests %>
	<h1>There aren't any contests yet, so <%= link_to "get voting!", new_contest_path %></h1>

<% else %>

<h1>Recent Contests,
	<span>

		<%= @range %>
	</spam>
</h1>

	<h2 class="blue">
	<% unless (@x - (@records) < 1) %>
		<%= link_to "< previous", contests_path( :range => prev_range ) %>
	<% end %>

	<% unless ( @contests.last.id == @first_record ) %>
		<%= link_to "next >", contests_path( :range => next_range ) %>
		</p>
	<% end %>
	</h2>

	<table class="table" id="recent-table">
		<tr>
			<th >Question</th>
			<th class="winner">Winner</th>
			<th class="loser">Loser</th>
		</tr>
		
		<% @contests.each do |contest| %>
		<tr>
			<td><%= link_to contest.question.text, question_path(contest.question.id) %><br><em>(<%= pretty_time(contest.created_at) %>)</em></td>
			<td class="winner"> <%= link_to (image_tag(contest.winner.image_path)), team_member_path(contest.winner.id) %></td>
			
			<td class="loser"> <%= link_to (image_tag(contest.loser.image_path)), team_member_path(contest.loser.id) %></td>
		</tr>
		<% end %>
		
	</table>
<% end %>

app/views/contests/new.html.erb
<%= render '/shared/alerts' %>
<h3 id="question" class="text-center"><%= @question.text %></h1>

<table class="table" id="contest_table">
	<tr>
		<td>
			<%= image_tag( @contestant_a.image_path, :class => "left medallion") %>
		</td>
		<td>
			<%= image_tag( @contestant_b.image_path, :class => "right medallion" ) %>
		</td>
	</tr>
	<tr>
	
		<td><%= button_to @contestant_a.name, {
		  :controller => "contests",	  
		  :action => "submit", 
		  :method => "post", 
		  :winner => @contestant_a.id,
		  :loser => @contestant_b.id,
		  :question => @question.id
		}, :class => "btn contest", :data => 'left' %></td>
		
		<td><%= button_to @contestant_b.name, {
		  :controller => "contests",		  
		  :action => "submit", 
		  :method => "post", 
		  :winner => @contestant_b.id,
		  :loser => @contestant_a.id,
		  :question => @question.id
		}, :class => "btn contest", :data => "right" %></td>
	</tr>

</table>

app/views/contests/show.html.erb
<h1><%= @question.text %></h1>

<table>
	<tr>
		<th>Contestant A</th>
		<th>Contestant B</th>
	</tr>
	<tr>
	
		<td><%= button_to @contestant_a.name, {
		  :controller => "contests", 
		  :action => "submit", 
		  :method => "post", 
		  :winner => @contestant_a.id,
		  :loser => @contestant_b.id,
		  :question => @question.id
		} %></td>
		
		<td><%= button_to @contestant_b.name, {
		  :controller => "contests", 
		  :action => "submit", 
		  :method => "post", 
		  :winner => @contestant_b.id,
		  :loser => @contestant_a.id,
		  :question => @question.id
		} %></td>
	</tr>

</table>