config/routes.rb
Schism::Application.routes.draw do
  root :to => "contests#new", :as => "schism"
  post "/submit", :to => "contests#submit"
  
  get "/login", "/register", "/sign-in", :to => "team_members#sign_in"
  post "/check_user", :to => "team_members#check_user"
  
  
  get "/logout", :to => "team_members#logout"
  
  resources :team_members, :path => "team"
  resources  :contests, :questions
  
  get "/team/:id/contests", :to => "team_members#contests", :as => "user_contests"
  
  match '/404' => 'errors#not_found'
  match '/422' => 'errors#server_error'
  match '/500' => 'errors#server_error'
  

end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  attr_accessible :email, :image_path, :name, :password_hash, :times_in_contests
  
  has_many :wins, {:class_name => 'Contest', :foreign_key => 'winner_id', :dependent => :destroy} 
  has_many :losses, {:class_name => 'Contest', :foreign_key => 'loser_id', :dependent => :destroy}
  
  validates_presence_of :name, :email
  
  
  #belongs_to :question, :through => :contests
  
  
  def self.random
    max = self.count 
	random = rand(max) + 1
    self.find random
  end
  
  def self.pick_two
    self.all.sample(2)
  end
  
  def self.biggest_streaker(group, option=:wins)
    group.sort do |a, b|
	  b.best_streak(option).length - a.best_streak(option).length
	end[0]
  end
  
  # returns the person with the most of a given attribute
  # pass an ActiveRecord collection of people and the attribute 
  # eg. TeamMember.with_most( group, :wins )
  
  def self.with_most(people, attribute)
    people.sort do |a,b|
	  b.send(attribute).length - a.send(attribute).length
	end[0]
  end
	
  def self.biggest_winner(people)
    self.with_most(people, :wins)
  end
  
  def self.biggest_loser(people)
    self.with_most(people, :losses)
  end
  
  def is?(other_team_member)
    self.id == other_team_member.id
  end
  
  def increment_contests
    self.times_in_contests += 1
	self.save
  end
  
  def signed_up?
    self.password_hash != nil
  end
  
  def to_s
    "#{self.name}, #{self.email}, #{self.image_path}"
  end
  
  def contests
	(self.wins + self.losses).sort {|a, b| a.created_at - b.created_at }
  end
  
  def winner?(contest)
    self.id == contest.winner.id
  end
  
  def loser?(contest)
    self.id == contest.loser.id
  end
  
  def in_contest?(contest)
    self.id == contest.winner.id || self.id == contest.loser.id
  end
  
  def opponent(contest)
    if self.winner?(contest)
	  opponent = contest.loser
	else
	  opponent = contest.winner
	end
	opponent
  end
  
  # returns the longest streak for that team_member
  # pass in :losses for losing streak
  def best_streak( option=:wins )
    s = self.streaks( option ).sort {|a, b| b.length - a.length }
	# if empty, return an empty array, rather than nil
	return [] if s.empty?
	s[0]
  end
  
  # returns an array of the team_member's streaks
  # each streak is itself an array of contests
  
  # NOTE: this version suffers from N+1 queries
  def streaks( option=:wins )
  
    # set the method to call according to the option passed in
    condition = option == :losses ? :loser? : :winner?
	
    s = self.contests.inject([[]]) do |streak, contest|
      if self.send(condition, contest)
	    streak[-1] << contest
		streak
	  else
	    streak << []
	  end
    end
	
	s.reject {|arr| arr.empty? }
  end
  
  # this version just returns a number
  def streaks_light( option=:wins )
    str = ""
	regex = option == :losses ? /w+/ : /l+/
#/
    s = self.contests.each { |contest| str << (self.id == contest.winner_id ? 'w' : 'l') }
	streaks = str.split(regex).compact
    return 0 if streaks.empty?
	streaks.sort.last.length
  end
  
  # uses the team_member.likelihoods method and trims its output 
  # to just outcomes greater than 1 vote
  def most_likely_to
    stats = self.likelihoods
	return [] if stats.empty?
    
	# removed the max condition, too restrictive
    # max = stats[0][1]

	stats.reject {|key, value| value < 2}
  end
  
  # as above, but the inverse
  def least_likely_to
    stats = self.likelihoods
	return [] if stats.empty?
	
	# min = stats[-1][1]
	stats.reject {|key, value| value > -2 }
  end
  
  # this method tallies likely and unlikely outcomes, 
  # and combines them in a single hash
  def likelihoods
    likely = self.tally(:wins)
	unlikely = self.tally(:losses)
	
	unlikely.each do |key, value|
	  likely[key] = (likely[key] || 0) - value
	end
	
	likely.sort_by {|key, value| value }.reverse
  end
  
  # returns a simple hash that tallies the votes the team_member received for each question
  # eg. { "Who would live longest?" => 2 }
  # pass in :losses to tally negative votes
  def tally(option=:wins)
    self.send(option).inject({}) do |hash, contest|
	  hash[contest.question.text] = (hash[contest.question.text] || 0) + 1
	  hash
	end
  end
  
  # IN PROGRESS -----------------------
  # this one returns an array of hashes
  # [ {"question" => "question_text", "id" => integer, "tally" => integer }, {...}, {...} ]
  
  #{ question_id: 1, question: "What if?", tally: 1 }
  
  def tally_with_id(option=:wins)
    self.send(option).inject({}) do |hash, contest|
	  obj = { 'question_id' => 1, 'count' => 1 }
	   obj['question_id'] = contest.question.id
	  
	   if hash[contest.question.text]
	     obj['count'] =  1
	   else
	     obj['count'] = 1
	   end
	  
	  hash[contest.question.text] = obj
	  hash
	end
  end
  
  
  def firstname
    self.name.split(" ")[0]
  end
  
  
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  include BCrypt
  
  def index
    unless logged_in?
      flash[:notice] = "You need to sign in to see the Quipper team."
    return redirect_to "/sign-in"
  end
    
  @team = TeamMember.includes(:wins, :losses).sort { |a,b| a.name <=> b.name }
  
  @biggest_winner = TeamMember.biggest_winner(@team)
  @biggest_loser = TeamMember.biggest_loser(@team)
  
  @best_streaker = get_best_streaker
  @best_streak = @best_streaker.streaks_light
  @worst_streaker = get_worst_streaker
  @worst_streak = @worst_streaker.streaks_light(:losses)
  
  end
  
  def show
    unless logged_in?
      flash[:notice] = "You need to sign in to view someone's profile."
      return redirect_to "/sign-in"
    end
  
    @team_member = TeamMember.find( params[:id])
    @heading = appellation
    
    @wins = @team_member.wins.includes(:question).all
    @losses = @team_member.losses.includes(:question).all
    
    @last_victory = @wins.last
    @last_defeat = @losses.last
    
    
    @win_streak = @team_member.streaks_light(:wins)
    @loss_streak = @team_member.streaks_light(:losses)
    
    if @team_member.most_likely_to 
      @likeliest = format_likelihoods( @team_member.most_likely_to )
    end
    
    if @team_member.least_likely_to
      @unlikeliest = format_likelihoods( @team_member.least_likely_to ).reverse
    end
  end
  
  def sign_in  
    # redirect if the user is already signed in
    return redirect_to team_member_path(session[:team_member_id]) if logged_in?
  
    render 'sign_in'
  end
  
  def contests
    @team_member = TeamMember.find( params[:id] )
    @contests = @team_member.contests
    @heading = "Contests"
  end
  

  def check_user
    email = params[:email] << "@quipper.com"
    @user = TeamMember.find_by_email( email )
    submitted_password = params[:password]
  
    if submitted_password.empty?
      flash[:alert] = "Enter a password, you crazy person."
      return redirect_to :back
    end
  
    # if the entered email address matches a user ...
    if @user
      # check if user has already registered (password exists)
      if @user.password_hash
        # check their password is correct
        if Password.new( @user.password_hash) == submitted_password 
      
          # flash[:notice] = "You've logged in as #{@user.name}"
          session[:team_member_id] = @user.id
          return redirect_to '/contests/new'
          
      else      
        flash[:alert] = "Email is registered, but not with that password."
        return redirect_to :back        
      end
      
        else
        # team_member found, but not registered yet
        # register their account
        hashed_password = Password.create( submitted_password )
        @user.update_attribute( :password_hash, hashed_password )
      
        flash[:notice] = "Account created for #{@user.name}!"
        session[:team_member_id] = @user.id
      
        redirect_to '/contests/new'
        end 
        
    else 
      flash[:alert] = "No user was found with that email address. Are you sure you work for Quipper?"
      redirect_to "/sign-in"
    end 
  end

  def logout
    session[:team_member_id] = nil
    redirect_to '/sign-in'
  end

  def get_best_streaker
    @team.sort {|a,b| b.streaks_light(:wins) - a.streaks_light(:wins) }.first
  end
  
  def get_worst_streaker
    @team.sort {|a,b| b.streaks_light(:losses) - a.streaks_light(:losses) }.first
  end
    
  
  private
  

  def appellation
    ["Quipper Colleague",
    "Quiz Stalwart",
    "Education Apostle",
    "Distributor of Wisdom",
    "Courier of Knowledge",
    "Knowledge Expert",
    "Thinker of Big Ideas",
    "Quipper Footsoldier", 
    "Learner", 
    "Professor of Truth and Light", 
    "Quasher of Ignorance"].sample(1)[0]
  end
  
  # receives a 2D array, should return pretty 1D array
  def format_likelihoods(arr)
    pretty = arr.map do |question, likelihood|
      [question.sub("Who would ", "").sub("?","").humanize, likelihood]
    end
    
    pretty
  end 
  
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/_team_stats.html.erb
<table class="table">
	<tr class="winner">
		<td>Biggest Winner:</td>
		<td class="small"> <%= portrait_link @biggest_winner %> <%= "#{@biggest_winner.firstname}, with #{@biggest_winner.wins.length} wins"%></td>
	</tr>
	<tr class="loser">
		<td>Biggest Loser:</td>
		<td class="small"> <%= portrait_link @biggest_loser %> <%= "#{@biggest_loser.firstname}, with #{@biggest_loser.losses.length} losses"%></td>
	</tr>
	<tr class="winner">
		<td>Best winning streak:</td>
		<td class="small"><%= portrait_link @best_streaker %> <%= "#{@best_streaker.firstname}, with #{@best_streak} wins in a row"%></td>
	</tr>
	<tr class="loser">
		<td>Worst losing streak:</td>
		<td class="small"><%= portrait_link @worst_streaker %> <%= "#{@worst_streaker.firstname}, with #{@worst_streak} losses in a row"%></td>
	</tr>	
</table>

app/views/team_members/contests.html.erb
<%= render '/shared/masthead' %>

<table id="team-member-table" class="table">
	<tr>
		<th colspan="2"></th>
	</tr>

	<% @contests.reverse.each do |contest| %>
		<% if @team_member.winner?(contest) %>
			<tr class="winner">
		<% else %>
			<tr class="loser">
		<% end %>
			<td>
				<%= link_to contest.question.text, question_path(contest.question.id) %> <em> (<%= pretty_time contest.created_at %>)</em>
			</td>
			<td class="small">
				<%= portrait_link( @team_member.opponent(contest) ) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/team_members/index.html.erb
<h1>The Team</h1>
<p>You've reached the TeamMember index. Well done, you.</p> 

<%= render 'team_stats' %>



<table class="table">
	<tr>
		<th></th>
		<th>Team Member</th>
		<th>Email</th>
	</tr>
	<% @team.each do |member| %>
	<% if member.signed_up? %>
		<tr class="neutral">
	<% else %>
		<tr>
	<% end %>
		<td><%= link_to image_tag(member.image_path), team_member_path(member.id) %></td>
		<td>
		<%= link_to member.name, team_member_path(member.id) %>
		</td>
		<td><%= mail_to member.email %></td>
	</tr>
	<% end %>
</table>

app/views/team_members/show.html.erb
<%= render '/shared/alerts' %>
<%= render '/shared/masthead' %>

<table class="table" id="profile-table">
	
	<tr>
		<td>
			Name: 
		</td>
		<td>
			<%= @team_member.name %>
		</td>
	</tr>
	
	<tr>
		<td>
			Email: 
		</td>
		<td>
			<%= mail_to @team_member.email %>
		</td>
	</tr>
	
	<tr >
		<td>
			<%= link_to "Contests:", user_contests_path( @team_member.id ) %> 
		</td>
		<td>
			<%= @team_member.times_in_contests %>
		</td>
	</tr>
	
	<tr class="winner">
		<td>
			Victories: 
		</td>
		<td>
			<%= @wins.count %>
		</td>
	</tr>
	
	<tr class="loser">
		<td>
			Defeats: 
		</td>
		<td>
			<%= @losses.count %>
		</td>
	</tr>
	
	<tr class="winner">
		<td>
			Best winning streak: 
		</td>
		<td>
			<% if @win_streak > 1 %>
				<%= @win_streak %>
			<% else %>
				None
			<% end %>
		</td>
	</tr>
	
	<tr class="loser">
		<td>
			Worst losing streak:
		</td>
		<td>
			<% if @loss_streak > 1 %>
				<%= @loss_streak %>
			<% else %>
				None
			<% end %>
		</td>
	</tr>	
	
	<tr class="winner">
		<td>
			Most likely to: 
		</td>
		<td>
			<% if @likeliest.empty? %>
			N/A				
				
			<% else %>
				<ul>
					<% @likeliest.each do |trait, value| %>
						<li class=>
							<%= trait %> <em>(<%= value %> votes)</em>
						</li>
					<% end %>
				</ul>
			<% end %>
		</td>
	</tr>
	
		<tr class="loser">
		<td>
			Least likely to: 
		</td>
		<td>
		<% if @unlikeliest.empty? %>
			N/A			
				
			<% else %>
			<ul>
				<% @unlikeliest.each do |trait, value| %>
					<li>
						<%= trait %><em> (<%= value %> votes)</em>
					</li>
				<% end %>
			</ul>
		<% end %>
		</td>
	</tr>
	
<% if @last_victory %>
	
	<tr class="winner">
		<th colspan="2">Most Recent Victory</th>

	</tr>
	
	<tr class="winner">
		<td><%= link_to @last_victory.question.text, question_path(@last_victory.question.id) %><em> (<%= pretty_time(@last_victory.created_at) %>)</em></td>
		<td class="text-center"><%= portrait_link @last_victory.loser %></td>
	</tr>
	
<% end %>

<% if @last_defeat %>
	
	<tr class="loser">
		<th colspan="2">Most Recent Defeat</th>
	</tr>
	
	<tr class="loser">
		<td><%= link_to @last_defeat.question.text, question_path(@last_defeat.question.id) %><em> (<%= pretty_time(@last_defeat.created_at) %>)</em></td>
		<td class="text-center"><%= portrait_link @last_defeat.winner %></td>
		
	</tr>
	
<% end %>

</table>

app/views/team_members/sign_in.html.erb
<div class="row">
<div class="col-md-3"></div>
<div class="col-md-6">
	<h1 class="text-center">Register or sign in.</h1>
	
	<div id="sign-in-alerts">
		<%= render '/shared/alerts' %>
	</div>
	
	<form id="sign-in-form" role="form" method="post" action="check_user">
		<div class="text-center">		
			<input class="my-input" type="text" name="email" id="email" placeholder="you"><label for="email"><span class="quipper">@quipper.com</span></label>
		</div>
		<div class=" form-group text-center">
			<label for="password"><spam class="quipper">Password:</span></label>
			<input class="my-input" type="password" name="password" id="password">
		</div>
		<br/>
		<div class="text-center"><input type="submit" class="btn sign-in" value="Sign in!"></div>
	</form>
</div>
<div class="col-md-3"></div>
</div>