config/routes.rb
Schism::Application.routes.draw do
  root :to => "contests#new", :as => "schism"
  post "/submit", :to => "contests#submit"
  
  get "/login", "/register", "/sign-in", :to => "team_members#sign_in"
  post "/check_user", :to => "team_members#check_user"
  
  
  get "/logout", :to => "team_members#logout"
  
  resources :team_members, :path => "team"
  resources  :contests, :questions
  
  get "/team/:id/contests", :to => "team_members#contests", :as => "user_contests"
  
  match '/404' => 'errors#not_found'
  match '/422' => 'errors#server_error'
  match '/500' => 'errors#server_error'
  

end

app/views/layouts/_navbar.html.erb
<div id="my_nav" class="navbar navbar-default navbar-static-top">
	<div class="container">
	
	<!-- <ul class="nav nav-bar">
				<% if controller?('contests') && action?('new') %>
					<li class="active">
				<% else %>
					<li>
				<% end %>					
				<%= link_to "Vote!", new_contest_path %></li>


				<% if controller?('contests') && action?('index') %>
					<li class="active">
				<% else %>
					<li>
				<% end %>					
				<%= link_to "Recent Contests", contests_path %></li>
	</ul> -->
	
	

		<div class="navbar-collapse collapse">
			<ul class="nav nav-bar">
				
				<% if controller?('contests') && action?('new') %>
					<li class="active">
				<% else %>
					<li>
				<% end %>					
				<%= link_to "Vote!", new_contest_path %></li>


				<% if controller?('contests') && action?('index') %>
					<li class="active">
				<% else %>
					<li>
				<% end %>					
				<%= link_to "Recent Contests", contests_path %></li>
				
				
				<% if controller?('team_members') && action?('index') %>
					<li class="active">
				<% else %>
					<li>
				<% end %>
				<%= link_to "Quipper Team", team_members_path %></li>
	
				<% if controller?('questions') && action?('index') %>
					<li class="active">
				<% else %>
					<li>
				<% end %>
				<%= link_to "Questions", questions_path %>
					</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">	
				<% if logged_in? %>
					<% if controller?('team_members') && action?('show') && id?(current_user.id) %>
						<li class="active">
					<% else %>
						<li>
					<% end %>
					
					<%= link_to (image_tag(current_user.image_path)), team_member_path(current_user.id), :class => "portrait" %></li>
					<li><%= link_to "Log-out", logout_path %></li>
				<% else %>
					<% if action?("sign_in") %>
						<li class="active">
					<% else %>
						<li>
					<% end %>	
					<%= link_to "Log in", login_path %></li>
				<% end %>
			</ul>
		</div>
		
	</div>
		

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Schism</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.css">
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body id="body">


<%= render "layouts/navbar" %>


<div class="container">


	
	<div class="row">
		<div class="col-md-1 col-lg-1"></div>
		<div class="col-md-10 col-lg-10">
			<%= yield %>
		</div>
		<div class="col-md-1 col-lg-1"></div>
	</div>
</div>
	
</body>
</html>